[package]
name = "metafs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.2"
bitvec = "1.0.1"
crc32fast = "1.3.2"
log = "0.4.17"
thiserror = "1.0.37"
